services:
  web:
    entrypoint: 
      - sleep
      - infinity
    build:
      context: .
      dockerfile: Dockerfile
    image: java-maven-dev
    container_name: maven-dev-container
    ports:
      - "8500:8500"
    depends_on:
      - db
    volumes:
      - ./repos:/root/repos
  db:
    container_name: mysql-web-container
    image: mysql:5.7.44
    environment:
      MYSQL_DATABASE: web
      MYSQL_PASSWORD: cuXjR5k*MpQ5GTg@*Ziqr7dwbwCSk%WMJmRK2RKmQj
      MYSQL_ROOT_PASSWORD: cuXjR5k*MpQ5GTg@*Ziqr7dwbwCSk%WMJmRK2RKmQj
      MYSQL_USER: mysql_web_usr
    ports:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./tmp:/tmp
  maria:
    container_name: mariadb-web-container
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: web
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_USER: root
    ports:
      - 3306
